### PR TITLE
Bypass codec when dealing with integers

### LINKED ISSUE #89: Bypassing codec for integer IDs
One of the things that bothers me since Storm moved to the `json` codec is that when using an integer ID with the AutoIncrement option on, the "natural" order is broken.

1, 2, 3, 4, ...10 will be ordered like this by BoltDB "1", "10", "2", "3", ...

I think that Storm should keep a natural order (that doesn't require any particular work) by using something like this in the [`toBytes`](https://github.com/asdine/storm/blob/master/storm.go#L117) function.

```
func itob(v int) []byte {
    b := make([]byte, 8)
    binary.BigEndian.PutUint64(b, uint64(v))
    return b
}
```
This example comes from the BoltDB [readme](https://github.com/boltdb/bolt#autoincrementing-integer-for-the-bucket)

Meaning that we should not use the Codec when dealing with integers for IDs and indexes.
We already do that for strings and slice of bytes.

The reason is because BoltDB already sorts the keys on writes, and because of the JSON codec we lose this free sort for nothing.

BoltDB guaranties that the keys will always be sorted 

> Bolt stores its keys in byte-sorted order within a bucket

⚠️ It is a breaking feature though

### PR DESCRIPTION
**Pull request by asdine**
Fixes #89

### CODE REVIEW

File: storm.go [hunk 1]
```diff
@@ -152,12 +153,26 @@ func toBytes(key interface{}, codec codec.MarshalUnmarshaler) ([]byte, error) {
...
-		return k, nil
-	}
-	if k, ok := key.(string); ok {
-		return []byte(k), nil
+	switch t := key.(type) {
+	case []byte:
+		return t, nil
+	case string:
+		return []byte(t), nil
+	case int:
```
Comment (bep) [inline storm.go]: I suspect you can collapse all the int cases into one line `case int, int64 ...:`. You should also consider adding the complete list.

File: storm.go [hunk 2]
```diff
@@ -152,12 +153,26 @@ func toBytes(key interface{}, codec codec.MarshalUnmarshaler) ([]byte, error) {
...
+		return itob(int(t)), nil
+	default:
+		return codec.Marshal(key)
 	}
+}
 
-	return codec.Marshal(key)
+func itob(v int) []byte {
+	b := make([]byte, 8)
+	binary.BigEndian.PutUint64(b, uint64(v))
```
Comment (bep) [inline storm.go]: This assumes all ID integers are `uints`. I guess that is the common case, but if this is a requirement, it should be documented.

File: storm.go (hunk 1 above)
Comment (asdine) [inline storm.go]: I thought the same at first, but the problem is that if i collapse, the `t` var won't be cast and i would have to reinfer it and cast it to int: https://play.golang.org/p/gMaR3HdZvr
and i can't use `fallthrough` either.
I'm gonna add the missing integer types, it's gonna be a long function...

File: storm.go (hunk 2 above)
Comment (asdine) [inline storm.go]: Mmmmm maybe we should use [`PutVarint`](https://golang.org/pkg/encoding/binary/#PutVarint) instead. It would allow people to use negative IDs if they want

Comment (asdine) [inline storm.go]: Wow actually it would have been a huge bug if i have let this like that. `toBytes` is also used for indexes, they marshal field values using `toBytes`

Comment (asdine) [inline storm.go]: Should be encode to the proper size according to the int size ?:
int8 -> 1 byte
int16 ->2 bytes
int32 -> 4 bytes
....
It would be more space efficient i guess?... But changing the ID type would break the compatibility
